version: "3.11"

services:
  db:
    container_name: postgres_demo
    image: postgres:alpine
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis_demo
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/var/lib/redis/data

  web:
    build: .
    volumes:
      - .:/distribution_service
      # - ./static:/distribution-service/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
      REDIS_URL: redis://redis:6379/0

volumes:
  redis-data:
  postgres_data:
