# Generated by Django 5.0.2 on 2024-02-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default='SuperUnique1', max_length=200)),
                ('payment_status', models.CharField(default='PENDING', max_length=200)),
                ('amount_gross', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amount_net', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order')),
            ],
        ),
    ]
