# Generated by Django 5.0.2 on 2024-02-14 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cart_items_alter_cart_user_alter_order_content_and_more'),
        ('payment', '0004_payment_current_user_payment_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount of the payment.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(help_text='The associated order for this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='PAY1111', help_text='Unique identifier for the payment transaction.', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='PENDING', help_text='Current status of the payment (e.g., PENDING, SUCCESSFUL, FAILED).', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processing_time_seconds',
            field=models.FloatField(default=5, help_text='The duration in seconds that the payment processing took.'),
        ),
    ]
