# Generated by Django 5.0.2 on 2024-02-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_remove_payment_order_delete_order_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointperformance',
            name='current_user',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='endpointperformance',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='endpointperformance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointperformance',
            name='git_commit',
            field=models.CharField(blank=True, default='external', max_length=112),
        ),
        migrations.AddField(
            model_name='endpointperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='endpointperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
