# Generated by Django 5.0.2 on 2024-02-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_endpointperformance_current_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointperformance',
            name='endpoint',
            field=models.CharField(help_text='The called endpoint', max_length=255),
        ),
    ]
