# Generated by Django 5.0.2 on 2024-02-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_endpointperformance_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointperformance',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='endpointperformance',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='endpointperformance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='endpointperformance',
            name='git_commit',
        ),
    ]
