# Generated by Django 5.0.2 on 2024-02-10 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.BigIntegerField(default=1001, unique=True)),
                ('status', models.CharField(default='unpaid', help_text='The status of the order can be New, Checkout, Paid, Failed, Shipped, Delivered, Returned, and Complete. (unpaid, paid, credited)', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='The total price of the Order including tax and shipping. It excludes the items discount.', max_digits=12)),
                ('content', models.CharField(blank=True, default='', help_text='The column used to store the additional details of the order.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
