# Generated by Django 5.0.2 on 2024-02-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='order', to='ice_cream.icecream'),
        ),
    ]
