# Generated by Django 5.0.2 on 2024-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_icecream_flavor'),
        ('order', '0002_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='ice_cream.icecream'),
        ),
    ]
