# Generated by Django 5.0.2 on 2024-02-14 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0008_alter_icecream_flavor_alter_icecream_uuid_slug'),
        ('order', '0005_cart_current_user_cart_deleted_cart_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(help_text='Items added to the cart.', related_name='cart', to='ice_cream.icecreamitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(help_text='cart owner.', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.CharField(blank=True, default='', help_text='Additional details of the order.', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(help_text='The user created this order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='The items associated with the order.', related_name='order', to='ice_cream.icecream'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(default=1001, help_text='Unique number to identify the order', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='unpaid', help_text='The status of the order can be Paid, unpaid. Other status like Failed, Shipped,                               Delivered, Returned, and Complete can be used accordingly.', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The total price of the Order.', max_digits=12),
        ),
    ]
