# Generated by Django 5.0.2 on 2024-02-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cart_items_alter_cart_user_alter_order_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='git_commit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='git_commit',
        ),
    ]
