# Generated by Django 5.0.2 on 2024-02-10 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='uuid_slug',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
