# Generated by Django 5.0.2 on 2024-02-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_icecream_uuid_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='flavor',
            field=models.CharField(default='chocolate', max_length=100),
        ),
    ]
