# Generated by Django 5.0.2 on 2024-02-14 02:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0007_icecream_current_user_icecream_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='flavor',
            field=models.CharField(default='chocolate', help_text='Ice cream flavour', max_length=100),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='uuid_slug',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='unique uuid identifier for the product'),
        ),
    ]
