# Generated by Django 5.0.2 on 2024-02-14 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0009_alter_icecream_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=3, help_text='Product price', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
