# Generated by Django 5.0.2 on 2024-02-14 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0011_alter_icecream_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='icecream',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='icecreamitem',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='icecreamitem',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='icecreamitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='icecreamitem',
            name='git_commit',
        ),
        migrations.AlterField(
            model_name='icecream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='flavor',
            field=models.CharField(default='chocolate', max_length=100),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='uuid_slug',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='icecreamitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='icecreamitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='git_commit',
        ),
    ]
