# Generated by Django 5.0.2 on 2024-02-14 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0012_alter_icecream_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='flavor',
            field=models.CharField(default='chocolate', help_text='Ice cream flavour', max_length=100),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='uuid_slug',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='unique uuid identifier for the product'),
        ),
        migrations.AlterField(
            model_name='icecreamitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='icecreamitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='icecream',
            unique_together={('title', 'uuid_slug')},
        ),
    ]
